version: "3"
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    working_dir: /srv/jekyll
    command: >
      bash -c "
        bundle install &&
        bundle exec jekyll serve --livereload --host 0.0.0.0 --port 8080"
